# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cfg/clocks.xdc

# XDC: imports/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_pll_0_0/system_pll_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_0/system_ps_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] -quiet

# IP: bd/system/ip/system_const_0_0/system_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_0_0 || ORIG_REF_NAME==system_const_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_0_0/system_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] -quiet

# IP: bd/system/ip/system_adc_0_0/system_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_adc_0_0 || ORIG_REF_NAME==system_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dac_0_0/system_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dac_0_0 || ORIG_REF_NAME==system_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_hub_0_0/system_hub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hub_0_0 || ORIG_REF_NAME==system_hub_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_0/system_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_0 || ORIG_REF_NAME==system_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_0/system_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_0 || ORIG_REF_NAME==system_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_phase_0_0/system_phase_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_phase_0_0 || ORIG_REF_NAME==system_phase_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dds_0_0/system_dds_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dds_0_0 || ORIG_REF_NAME==system_dds_0_0} -quiet] -quiet

# IP: bd/system/ip/system_lfsr_0_0/system_lfsr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lfsr_0_0 || ORIG_REF_NAME==system_lfsr_0_0} -quiet] -quiet

# IP: bd/system/ip/system_mult_0_0/system_mult_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mult_0_0 || ORIG_REF_NAME==system_mult_0_0} -quiet] -quiet

# IP: bd/system/ip/system_bcast_0_1/system_bcast_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_0_1 || ORIG_REF_NAME==system_bcast_0_1} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_0/system_cic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_0 || ORIG_REF_NAME==system_cic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fifo_0_0/system_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fifo_0_0 || ORIG_REF_NAME==system_fifo_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_1/system_cic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_1 || ORIG_REF_NAME==system_cic_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_0_0/system_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_0_0 || ORIG_REF_NAME==system_fir_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_iq_pack_0_0/system_gmsk_iq_pack_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_iq_pack_0_0 || ORIG_REF_NAME==system_gmsk_iq_pack_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_iq_unpack32_0_1/system_gmsk_iq_unpack32_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_iq_unpack32_0_1 || ORIG_REF_NAME==system_gmsk_iq_unpack32_0_1} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_axis_broadcast2_0_4/system_gmsk_axis_broadcast2_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_axis_broadcast2_0_4 || ORIG_REF_NAME==system_gmsk_axis_broadcast2_0_4} -quiet] -quiet

# IP: bd/system/ip/system_cmpy_discriminator_0_0/system_cmpy_discriminator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cmpy_discriminator_0_0 || ORIG_REF_NAME==system_cmpy_discriminator_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_discriminator_p_0_1/system_gmsk_discriminator_p_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_discriminator_p_0_1 || ORIG_REF_NAME==system_gmsk_discriminator_p_0_1} -quiet] -quiet

# IP: bd/system/ip/system_cordic_0_1/system_cordic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cordic_0_1 || ORIG_REF_NAME==system_cordic_0_1} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_soft_scale_0_2/system_gmsk_soft_scale_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_soft_scale_0_2 || ORIG_REF_NAME==system_gmsk_soft_scale_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axis_lfsr_0_1/system_axis_lfsr_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_lfsr_0_1 || ORIG_REF_NAME==system_axis_lfsr_0_1} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_pad32_0_0/system_gmsk_pad32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_pad32_0_0 || ORIG_REF_NAME==system_gmsk_pad32_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_axis_broadcast2_0_1/system_gmsk_axis_broadcast2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_axis_broadcast2_0_1 || ORIG_REF_NAME==system_gmsk_axis_broadcast2_0_1} -quiet] -quiet

# IP: bd/system/ip/system_port_slicer_0_6/system_port_slicer_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_port_slicer_0_6 || ORIG_REF_NAME==system_port_slicer_0_6} -quiet] -quiet

# IP: bd/system/ip/system_phase_slice_disc_0_0/system_phase_slice_disc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_phase_slice_disc_0_0 || ORIG_REF_NAME==system_phase_slice_disc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_squelch_0_0/system_gmsk_squelch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_squelch_0_0 || ORIG_REF_NAME==system_gmsk_squelch_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_axis_mux2_0_2/system_gmsk_axis_mux2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_axis_mux2_0_2 || ORIG_REF_NAME==system_gmsk_axis_mux2_0_2} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_reset_rafaga_0_0/system_gmsk_reset_rafaga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_reset_rafaga_0_0 || ORIG_REF_NAME==system_gmsk_reset_rafaga_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_squelch_debounce_0_0/system_gmsk_squelch_debounce_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_squelch_debounce_0_0 || ORIG_REF_NAME==system_gmsk_squelch_debounce_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_squelch_autocal_0_0/system_gmsk_squelch_autocal_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_squelch_autocal_0_0 || ORIG_REF_NAME==system_gmsk_squelch_autocal_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_pad32_0_4/system_gmsk_pad32_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_pad32_0_4 || ORIG_REF_NAME==system_gmsk_pad32_0_4} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_nrzi_decode_0_0/system_gmsk_nrzi_decode_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_nrzi_decode_0_0 || ORIG_REF_NAME==system_gmsk_nrzi_decode_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_bit_pack32_0_0/system_gmsk_bit_pack32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_bit_pack32_0_0 || ORIG_REF_NAME==system_gmsk_bit_pack32_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_slicer_0_0/system_gmsk_slicer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_slicer_0_0 || ORIG_REF_NAME==system_gmsk_slicer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cordic_cfo_0/system_cordic_cfo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cordic_cfo_0 || ORIG_REF_NAME==system_cordic_cfo_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_delay_line_0_0/system_gmsk_delay_line_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_delay_line_0_0 || ORIG_REF_NAME==system_gmsk_delay_line_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_symbol_strobe_0_1/system_gmsk_symbol_strobe_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_symbol_strobe_0_1 || ORIG_REF_NAME==system_gmsk_symbol_strobe_0_1} -quiet] -quiet

# IP: bd/system/ip/system_osc_0_1/system_osc_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_osc_0_1 || ORIG_REF_NAME==system_osc_0_1} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_dc_tracker_1_0/system_gmsk_dc_tracker_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_dc_tracker_1_0 || ORIG_REF_NAME==system_gmsk_dc_tracker_1_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_tau_to_fase_0_0/system_gmsk_tau_to_fase_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_tau_to_fase_0_0 || ORIG_REF_NAME==system_gmsk_tau_to_fase_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_axis_broadcast2_0_0/system_gmsk_axis_broadcast2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_axis_broadcast2_0_0 || ORIG_REF_NAME==system_gmsk_axis_broadcast2_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_symbol_phase_ac_0_0/system_gmsk_symbol_phase_ac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_symbol_phase_ac_0_0 || ORIG_REF_NAME==system_gmsk_symbol_phase_ac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_iq_pack_0_1/system_gmsk_iq_pack_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_iq_pack_0_1 || ORIG_REF_NAME==system_gmsk_iq_pack_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_0_2/system_fir_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_0_2 || ORIG_REF_NAME==system_fir_0_2} -quiet] -quiet

# IP: bd/system/ip/system_port_slicer_0_4/system_port_slicer_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_port_slicer_0_4 || ORIG_REF_NAME==system_port_slicer_0_4} -quiet] -quiet

# IP: bd/system/ip/system_port_slicer_0_5/system_port_slicer_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_port_slicer_0_5 || ORIG_REF_NAME==system_port_slicer_0_5} -quiet] -quiet

# IP: bd/system/ip/system_axi_hub_0_0/system_axi_hub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hub_0_0 || ORIG_REF_NAME==system_axi_hub_0_0} -quiet] -quiet

# IP: bd/system/ip/system_port_slicer_0_0/system_port_slicer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_port_slicer_0_0 || ORIG_REF_NAME==system_port_slicer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slicer_reset_0/system_slicer_reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slicer_reset_0 || ORIG_REF_NAME==system_slicer_reset_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_0/system_rst_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_0 || ORIG_REF_NAME==system_rst_slice_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_fifo_0_1/system_axis_fifo_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_fifo_0_1 || ORIG_REF_NAME==system_axis_fifo_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axis_ram_reader_1_0/system_axis_ram_reader_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_ram_reader_1_0 || ORIG_REF_NAME==system_axis_ram_reader_1_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_selector8_0_0/system_gmsk_selector8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_selector8_0_0 || ORIG_REF_NAME==system_gmsk_selector8_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_pad32_habilitado_0/system_gmsk_pad32_habilitado_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_pad32_habilitado_0 || ORIG_REF_NAME==system_gmsk_pad32_habilitado_0} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_pad32_habilitado_1/system_gmsk_pad32_habilitado_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_pad32_habilitado_1 || ORIG_REF_NAME==system_gmsk_pad32_habilitado_1} -quiet] -quiet

# IP: bd/system/ip/system_gmsk_pad32_piso_ruido_0/system_gmsk_pad32_piso_ruido_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmsk_pad32_piso_ruido_0 || ORIG_REF_NAME==system_gmsk_pad32_piso_ruido_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_2/system_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_0_2 || ORIG_REF_NAME==system_xlconstant_0_2} -quiet] -quiet

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_ooc.xdc

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_ps_0_0/system_ps_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_dds_0_0/system_dds_0_0_ooc.xdc

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_mult_0_0/system_mult_0_0_ooc.xdc

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_bcast_0_1/system_bcast_0_1_ooc.xdc

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_cic_0_0/system_cic_0_0_ooc.xdc

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_fir_0_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_0_0 || ORIG_REF_NAME==system_fir_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_fir_0_0/system_fir_0_0_ooc.xdc

# XDC: d:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/ip/system_fir_0_2/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_0_2 || ORIG_REF_NAME==system_fir_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: D:/Vivado/AIS_Receiver_GMSK_Demod_No_CFO/AIS_Receiver_GMSK_Demod_No_CFO.gen/sources_1/bd/system/system_ooc.xdc
